apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
  namespace: logistics-demo
  labels:
    app: inventory-service
data:
  database_url: "postgresql://postgres:demo_password_123@postgresql:5432/inventory_db"
  rabbitmq_url: "amqp://admin:admin_password_123@rabbitmq:5672/"
