apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: logistics-demo
  labels:
    app: rabbitmq
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: admin
  RABBITMQ_DEFAULT_PASS: admin_password_123
