apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: logistics-demo
  labels:
    app: order-service
data:
  DATABASE_URL: "postgresql://postgres:demo_password_123@postgresql:5432/orders_db"
  RABBITMQ_URL: "amqp://admin:admin_password_123@rabbitmq:5672/"
  INVENTORY_SERVICE_URL: "http://inventory-service:8003"
  LOG_LEVEL: "INFO"
