apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: logistics-demo
  labels:
    app: notification-service
data:
  database_url: "postgresql://postgres:demo_password_123@postgresql:5432/notifications_db"
  rabbitmq_url: "amqp://admin:admin_password_123@rabbitmq:5672/"
